version: 0.2

env:
  variables:
    IMAGE_NAME: octobeehive/cicd
  secrets-manager:
    PRIVKEY: BeehivePrivkey
    FULLCHAIN: BeehiveFullchain
    DOCKERRUN: BeehiveDockerrun
    DATABASE: BeehiveDatabaseConfig

phases:
  build:
      #Build and Push image to OCTO Dockerhub
    commands:
      - echo $PRIVKEY > config/apache2/privkey.pem
      - echo $FULLCHAIN > config/apache2/fullchain.pem
      - echo $DATABASE > config/database.yml
      - docker build -t $IMAGE_NAME:latest .
      - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASS
      - docker push $IMAGE_NAME:latest
  post_build:
    commands:
      - echo $DOCKERRUN
      - echo $FULLCHAIN
      - echo $PRIVKEY
      - echo $DOCKERRUN > Dockerrun.aws.json
artifacts:
  files:
    - Dockerrun.aws.json

