version: 2.1
orbs:
  awsebcli: sbc-orbs/awsebcli@0.0.3
jobs:
  build:
    environment:
      IMAGE_NAME: octobeehive/cicd
    docker:
      - image: circleci/ruby:2.5.6
    steps:
      - checkout
      - setup_remote_docker

      #Build and Push image to OCTO Dockerhub
      - run: |
          touch config/database.yml
          docker build -t $IMAGE_NAME:latest .
          docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASS
          docker push $IMAGE_NAME:latest
  # display_env:
  #   steps:
  #     - checkout
  #     - run: |
  #         echo $DOCKERRUN
  #         echo $FULLCHAIN
  #         echo $PRIVKEYi
  # deploy:
  #   steps:
  #     - checkout
  #     - awsebcli/install
     



