version: 2.1
orbs:
  awsebcli: sbc-orbs/awsebcli@0.0.3
jobs:
  build:
    environment:
      IMAGE_NAME: octobeehive/cicd
    docker:
      - image: circleci/ruby:2.5.6
    steps:
      - checkout
      - setup_remote_docker

      #Build and Push image to OCTO Dockerhub
      - run: |
          touch config/database.yml
          docker build -t $IMAGE_NAME:latest .
          docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASS
          docker push $IMAGE_NAME:latest
  display_env:
    steps:
      - checkout
      - run: |
          echo $DOCKERRUN
          echo $FULLCHAIN
          echo $PRIVKEYi
  install_dependencies:
    description: |
      Install the AWS CLI via pip.
    steps:
      - run:
          name: Install Python and Pip
          command: |
            sudo apt-get -y -qq install python3.5-dev
            sudo curl -O https://bootstrap.pypa.io/get-pip.py
            sudo python3.5 get-pip.py
      - run:
          name: Install AWS and AWS EB CLIs
          command: |
            export PIP=$(which pip pip3 | head -1)
            if [[ -n $PIP ]]; then
              if which sudo > /dev/null; then
                sudo $PIP install awscli awsebcli --upgrade
              else
                # This installs the AWS CLI to ~/.local/bin. Make sure that ~/.local/bin is in your $PATH.
                $PIP install aws --upgrade --user
              fi
            elif [[ $(which unzip curl | wc -l) -eq 2 ]]; then
              cd
              curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
              unzip awscli-bundle.zip
              if which sudo > /dev/null; then
                sudo ~/awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
              else
                # This installs the AWS CLI to the default location (~/.local/lib/aws) and create a symbolic link (symlink) at ~/bin/aws. Make sure that ~/bin is in your $PATH.
                awscli-bundle/install -b ~/bin/aws
              fi
              rm -rf awscli-bundle*
              cd -
            else
              echo "Unable to install AWS CLI. Please install pip."
              exit 1
            fi
     



