version: 2.1

# orbs:
#   awsebcli: sbc-orbs/awsebcli@0.0.3
orbs:
  common-beanstalk: mgmorbs/common-beanstalk@0.11.0
  
jobs:
  build:
    environment:
      IMAGE_NAME: octobeehive/cicd
    docker:
      - image: circleci/ruby:2.5.6
    steps:
      - checkout
      - setup_remote_docker

      #Build and Push image to OCTO Dockerhub
      - run: |
          touch config/database.yml
          # docker build -t $IMAGE_NAME:latest .
          # docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASS
          # docker push $IMAGE_NAME:latest
  display_env:
    docker:
      - image: circleci/ruby:2.5.6
    steps:
      - checkout
      - run: |
          echo $DOCKERRUN
          echo $FULLCHAIN
          echo $PRIVKEY
  deploy:
    docker:
      - image: circleci/ruby:2.5.6
    steps:
      - checkout
      #- awsebcli/install
      - common-beanstalk/install-awscli:
          install-eb-cli: true

workflows:
  build-test-deploy:
    jobs:
      - build 
      - display_env
      - deploy:
          requires:
            - build
     



